table:
  name: environments
  schema: app
select_permissions:
  - role: app
    permission:
      columns:
        - app_id
        - created_at
        - id
        - key
        - preview
      filter:
        app_id:
          _eq: X-Hasura-App-Id
      limit: 200
